---
- name: Installation & Configuration of Prometheus
  hosts: prometheus
  vars:
    version: "2.0.0"
  environment:
    https_proxy: 
  tasks:
    - name: Download the latest version of Prometheus.
      get_url: url=https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz dest=/tmp use_proxy=yes
    - name: Unzip the Prometheus file.
      unarchive: src=/tmp/prometheus-{{ version }}.linux-amd64.tar.gz dest=/etc remote_src=yes
    - name: Generate service file and copy it to prometheus node.
      template: src=../templates/prometheus.service.j2 dest=/etc/systemd/system/prometheus.service owner=root mode=u+rwx
    - name: Generate and load prometheus configuration file.
      template: src=../templates/prometheus.yml.j2 dest=/etc/prometheus-{{ version }}.linux-amd64/prometheus.yml
    - name: Reload the daemon.
      shell: systemctl daemon-reload
    - name: Start the Agent.
      service: name=prometheus state=restarted enabled=yes
