
---
- name: Installation & Configuration of Grafana
  hosts: prometheus
  vars:
    version: "4.6.2-1"
  environment:
    https_proxy: 
  tasks:
    - name: Download grafana.
      get_url: url=https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-{{ version }}.x86_64.rpm  dest=/tmp use_proxy=yes
    - name: Install Grafana locally.
      yum: name=/tmp/grafana-{{ version }}.x86_64.rpm state=present
    - name: Configure grafana config file.
      template: src=../templates/grafana.ini.j2 dest=/etc/grafana/grafana.ini
    - name: Start Grafana.
      service: name=grafana-server state=restarted enabled=yes
